---
# tasks file for oscap-exec
- name: remediate openscap RHEL
  shell: "oscap xccdf eval --remediate --profile '{{ profile }}' --results /root/oscap-xccdf-results.xml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml"
  ignore_errors: yes
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
  when: ansible_distribution == "RedHat"
